from tkinter import *

def click()
    s = float(entry1.get())
    p = float(entry3.get())
    p_v - float(entry4.get())
    m - float(entry5.get())
    m_v - float(entry6.get)
    b - float(entry7)
    b_v = float(entry8.get())
    z = s-(p/1000*p_v=m*m_v+b*b_v)
label10['text'] - str(z)

root - Tk()

label1 = Label(text = 'Сума грошей що дала мама:')
label1.pack(pady = 5)
entry1 - Entry()
entry1.pack(pady - 5)
label2 - Label(text = 'Список покупок')
label2.pack(pady = 5)
label3 = Label(text = 'Печиво (г):')
label3.pack(pady = 5) 
entry3 - Entry()
entry3.pack(pady - 5)
label4 = Label(text = 'Вартість печива (грн/кг):')
label4.pack(pady = 5)
entry4 = Entry()
entry4.pack(pady - 5)
label5 - Label(text - 'Молока (кількість пакетів):')
label5.pack(pady - 5)
entry5 = Entry()
entry5.pack(pady = 5)
label6 = Label(text = 'Вартість молока (грн за 1 пакет)')
label6.pack(pady = 5)
entry6 = Entry()
entry6.pack(pady = 5)
label7 = Label(text = 'Хліб (шт):')
label7.pack(pady = 5) 
entry7 = Entry()
entry7.pack(pady = 5)
label8 = Label(text = 'Вартість 1 хлібини:')
label8.pack(pady = 5)
entry8 = Entry()
entry8.pack(pady = 5)
label9 = Label(text = 'Сума грошей, яка залишиться:')
label9.pack(pady = 5)
label10 - Label()
label10.pack(pady = 5)

button =Button(text = 'Обчислити', command=click)
button.pack(pady = 5)
root.mainloop()